// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD15mXXMW_xoXdHRxLemZWd650vwjWo8c4',
    appId: '1:137311307266:web:f4111373110a3f949a091b',
    messagingSenderId: '137311307266',
    projectId: 'hirschboeoeg',
    authDomain: 'hirschboeoeg.firebaseapp.com',
    databaseURL: 'https://hirschboeoeg-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hirschboeoeg.appspot.com',
    measurementId: 'G-LZVMTZPWD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbcj10Kz_Po7LAC8xZuU84q5Agtd31Xro',
    appId: '1:137311307266:android:fb1e4de6e018d51f9a091b',
    messagingSenderId: '137311307266',
    projectId: 'hirschboeoeg',
    databaseURL: 'https://hirschboeoeg-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hirschboeoeg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfyWOwZUvV7bW2fWHXfLpYZFWlJIV8ZK4',
    appId: '1:137311307266:ios:6257f13cf3c637b49a091b',
    messagingSenderId: '137311307266',
    projectId: 'hirschboeoeg',
    databaseURL: 'https://hirschboeoeg-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hirschboeoeg.appspot.com',
    iosClientId: '137311307266-ifn7pp3retfojit1riphio12bvabn615.apps.googleusercontent.com',
    iosBundleId: 'com.philnue.firebasetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfyWOwZUvV7bW2fWHXfLpYZFWlJIV8ZK4',
    appId: '1:137311307266:ios:6257f13cf3c637b49a091b',
    messagingSenderId: '137311307266',
    projectId: 'hirschboeoeg',
    databaseURL: 'https://hirschboeoeg-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hirschboeoeg.appspot.com',
    iosClientId: '137311307266-ifn7pp3retfojit1riphio12bvabn615.apps.googleusercontent.com',
    iosBundleId: 'com.philnue.firebasetest',
  );
}
